# Site settings
title: Tali Takes Tech
header-img: img/home-bg.png
email: talikuhel@gmail.com
copyright_name: talikuhel
description: > # this means to ignore newlines until "baseurl:"
  UI Writer. Poet. User centric development.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: tali_kuhel
github_username:  talikuhel
learn_profile: talikuhel
email_username: talikuhel@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
